/**
 * Shared type definitions for GovMatch.
 *
 * Reminder on the data contract: every dollar amount, date, deadline, and URL
 * originates from an official API response or from the hardcoded constants in
 * officialLinks.ts. When a field is unknown, it is `null` — never invented.
 */

export type Language = "en" | "es";

export interface StartupProfile {
  industry: string | null;
  location: string | null;
  employees: string | null;
  revenue: string | null;
  raised: string | null;
  fundingNeed: string | null;
  useOfFunds: string | null;
}

export interface GovernmentTerms {
  keywords: string[];
  themes: string[];
}

export interface AnalyzeResult {
  profile: StartupProfile;
  governmentTerms: GovernmentTerms;
}

/**
 * An Opportunity is built ONLY from fields returned by the Grants.gov API.
 * Missing values are null, never Claude-filled.
 */
export interface Opportunity {
  opportunityNumber: string;
  title: string;
  agency: string | null;
  description: string | null;
  eligibility: string | null;
  deadline: string | null;
  awardCeiling: number | null;
  awardFloor: number | null;
  sourceUrl: string | null;
  /**
   * Grants.gov internal numeric id (from search2). Used ONLY to call
   * fetchOpportunity for the specific FOA's detail. Never shown to the user.
   */
  internalId?: string | null;
  /** Grants.gov status: "posted" (open) or "forecasted" (upcoming). */
  status?: string | null;
  /** Eligible applicant type descriptions declared by the FOA (from the API). */
  applicantTypes?: string[];
  /** NIH/agency activity code parsed from the title/number (e.g. R01, R43). */
  activityCode?: string | null;
  /** Funding instrument/type from the API (e.g. "Grant"), never Claude-invented. */
  fundingType?: string | null;
  /** Provenance — always the specific endpoint the data came from. */
  source?: "Grants.gov";
  /** ISO timestamp of when GovMatch last retrieved this from the source. */
  lastCheckedAt?: string;
}

export interface SampleAward {
  recipient: string | null;
  amount: number | null;
  agency: string | null;
  awardType: string | null;
  date: string | null;
  program: string | null;
}

/**
 * Historical evidence lives SEPARATELY from opportunities.
 * "Historical recipients" counts who received funding from the program — it is
 * NOT a claim that those recipients resemble this specific startup.
 */
export interface HistoricalEvidence {
  historicalRecipients: number | null;
  medianAward: number | null;
  largestAward: number | null;
  sampleAwards: SampleAward[];
  source: "USAspending.gov";
}

/**
 * TWO SEPARATE AXES, judged by ONE consistent rule for every opportunity:
 *
 *  1. eligibilityStatus — CAN this entity type LEAD it? (code; official data only)
 *  2. strategicFit      — how well it suits the applicant's STAGE (high/moderate/low)
 *
 * strategicFit NEVER changes eligibilityStatus. An eligible-but-low-fit research
 * grant stays "eligible", shown as e.g. "Eligible to lead · Low strategic fit".
 */
export type StrategicFit = "high" | "moderate" | "low";

/** Legacy alias kept for any older imports. */
export type MatchStrength = "strong" | "possible" | "weak";

export type EligibilityStatus =
  | "eligible"
  | "possible"
  | "ineligible"
  | "premature" // eligible type, but a hard prerequisite isn't met (e.g. prior Phase II)
  | "requires_verification";

/** One traceable eligibility check: an official requirement vs a company fact. */
export interface EligibilityReason {
  requirement: string;
  companyFact: string;
  result: "passes" | "fails" | "unknown";
  source: string; // e.g. "Grants.gov applicant types"
}

export interface WhyItMatches {
  dimension: string;
  status: string; // "✓" | "~" | "✗"
  detail: string;
}

export interface DetailPoint {
  detail: string;
}

export interface OpportunityMatch {
  id: string; // opportunityNumber
  /** Axis 2 — strategic fit for the applicant's stage (Claude, code-capped). */
  strategicFit: StrategicFit;
  /** Axis 1 — eligibility to LEAD, determined by CODE with traceable reasons. */
  eligibilityStatus: EligibilityStatus;
  eligibilityReasons: EligibilityReason[];
  whyItMatches: WhyItMatches[];
  whyItMayNotMatch: DetailPoint[];
  possibleBlockers: DetailPoint[];
  whatToVerify: DetailPoint[];
  nextSteps: DetailPoint[];
}

/** Code-computed counts, always derived from the exact displayed match array. */
export interface MatchCounts {
  reviewed: number; // opportunities handed to the matcher
  shown: number; // opportunities displayed
  filtered: number; // removed before/at ranking (e.g. off-domain)
  highFit: number;
  moderateFit: number;
  lowFit: number;
  eligible: number;
  ineligibleOrVerify: number;
}

export interface MatchResult {
  matches: OpportunityMatch[];
  /** Code-computed counts (never generated by Claude). */
  counts: MatchCounts;
  /**
   * Honest overall verdict. When nothing fits well, honestNoMatch is true and
   * `summary` explains why. This is PROSE only — it must contain no numeric
   * counts (those come from `counts`).
   */
  honestNoMatch: boolean;
  summary: string;
}

/* ----------------------------- Application plan ---------------------------- */

export interface PrefillField {
  key: string;
  value: string;
  sensitive: boolean;
}

export interface PrefillDraft {
  key: string;
  label: string;
  /** Draft written in the active language. */
  value: string;
  /** English version ready to paste into official (English-only) forms. */
  english?: string;
}

export interface PrefillData {
  fields: PrefillField[];
  drafts: PrefillDraft[];
}

export interface RegistrationItem {
  task: string;
  whatItIs: string;
  activeTime: string | null;
  waitTime: string | null;
  warning: string | null;
  /** Supplied by CODE from OFFICIAL_LINKS — Claude does not produce this. */
  officialLink?: string | null;
}

export interface EligibilityItem {
  question: string;
  yesNoImpact: string;
}

export interface DocumentItem {
  document: string;
  whatItIs: string;
  howToGet: string;
  activeTime: string | null;
}

export interface DraftingSection {
  sectionName: string;
  draft: string;
  english?: string;
}

export interface FinalPackageItem {
  task: string;
  detail: string;
}

export interface ApplicationPhase {
  name: string;
  items?: (RegistrationItem | EligibilityItem | DocumentItem | FinalPackageItem)[];
  sections?: DraftingSection[];
}

export interface ApplicationPlan {
  phases: ApplicationPhase[];
  prefillData: PrefillData;
}

/* --------------------------- Dynamic (per-FOA) plan ------------------------ */
/**
 * The plan is generated from what EACH specific opportunity officially declares
 * (fetchOpportunity) plus the fixed base-registration constants — never a fixed
 * template. Anything the FOA doesn't cover becomes a "verify-official" step.
 */

export interface SubmissionSystem {
  name: string;
  officialUrl: string | null;
  note: string;
}

export interface BaseRegistrationStep {
  task: string;
  whatItIs: string;
  officialLink: string | null; // supplied by CODE from OFFICIAL_LINKS
  activeTime: string | null;
  waitTime: string | null;
  warning: string | null;
}

export type StepSource = "FOA" | "verify-official";

export interface DynamicStep {
  stepType: string;
  title: string;
  whatItIs: string;
  source: StepSource;
  officialLink: string | null;
  activeTime: string | null;
  waitTime: string | null;
  warning: string | null;
  /** Why this step appears for THIS FOA (e.g. "FOA declares an LOI due Sep 3"). */
  conditionReason: string;
}

export interface RequiredForm {
  formName: string;
  source: "Package" | "verify-official";
}

export interface EligibilityGateItem {
  question: string;
  ifFailImpact: string;
}

export interface PlanDraft {
  sectionName: string;
  draft: string;
  english?: string;
}

export interface DynamicPlan {
  opportunityId: string;
  submissionSystem: SubmissionSystem;
  baseRegistrations: BaseRegistrationStep[];
  dynamicSteps: DynamicStep[];
  requiredForms: RequiredForm[];
  eligibilityGate: EligibilityGateItem[];
  drafts: PlanDraft[];
  prefillData: { fields: PrefillField[] };
  /** True when fetchOpportunity failed and we fell back to base + verify step. */
  degraded?: boolean;
}

/* ------------------------------ Wizard state ------------------------------ */

export type ChecklistStatus = "pending" | "in_progress" | "done";

/** Per-opportunity persisted progress, keyed in localStorage by opportunity id. */
export interface SavedProgress {
  opportunityId: string;
  currentPhase: number;
  checklist: Record<string, ChecklistStatus>;
  editedDrafts: Record<string, string>;
  updatedAt: string;
}
